# README FIRST
# 1. replace "NAMESPACE" and "COLLECTION_NAME" with the correct name in the env section (e.g. with 'community' and 'mycollection')
# 2. If you don't have unit tests remove that section
# 3. If your collection depends on other collections ensure they are installed, see "Install collection dependencies"
# If you need help please ask in #ansible-community on the Libera.chat IRC network

name: CI
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - master
  pull_request:
  # Run CI once a week (at 06:00 UTC on friday)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-core version
  schedule:
    - cron: '0 6 * * 5'
env:
  NAMESPACE: yoanm
  COLLECTION_NAME: utils

jobs:

###
# Sanity tests (REQUIRED)
#
# https://docs.ansible.com/ansible/latest/dev_guide/testing_sanity.html

  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          # It's important that Sanity is tested against all stable-X.Y branches
          # Testing against `devel` may fail as new tests are added.
        # - stable-2.9 # Only if your collection supports Ansible 2.9
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - devel
    runs-on: ubuntu-latest
    steps:

      # ansible-test requires the collection to be in a directory in the form
      # .../ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/

      - name: Check out code
        uses: actions/checkout@v2
#        with:
#          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # it is just required to run that once as "ansible-test sanity" in the docker image
          # will run on all python versions it supports.
          python-version: 3.8

      # Install the head of the given branch (devel, stable-2.10)
      - name: Install ansible-core (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
#      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
#        continue-on-error: true

      - name: Build collection
        run: make configure-test-ansible
        if: ${{ matrix.ansible != 'stable-2.10' }}

      - name: Build collection for ansible-core v2.10
        # ansible-core v2.10 doesn't support installing fom current directory if it is not under NAMESPACE/NAME directories
        run: make clean && make build && ansible-galaxy collection install -p ./build/ansible_collections "$(find . -name "${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-*.tar.gz")" && cd build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}} && git init .
        if: ${{ matrix.ansible == 'stable-2.10' }}

      # run ansible-test sanity inside of Docker.
      # The docker container has all the pinned dependencies that are required
      # and all python versions ansible supports.
      - name: Run sanity tests
        run: pwd && ansible-test sanity --docker -v --color --coverage
        working-directory: ./build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      # ansible-test support producing code coverage date
      - name: Generate coverage report
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version
        working-directory: ./build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      # See the reports at https://codecov.io/gh/yoanm/ansible-utils-collection
#      - uses: codecov/codecov-action@v2
#        with:
#          fail_ci_if_error: false

###
# Unit tests (OPTIONAL)
#
# https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html

#  units:
#    runs-on: ubuntu-latest
#    name: Units (Ⓐ${{ matrix.ansible }})
#    strategy:
#      # As soon as the first unit test fails, cancel the others to free up the CI queue
#      fail-fast: true
#      matrix:
#        ansible:
#          # - stable-2.9 # Only if your collection supports Ansible 2.9
#          - stable-2.10
#          - stable-2.11
#          - stable-2.12
#          - devel

#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#        with:
#          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          # it is just required to run that once as "ansible-test units" in the docker image
#          # will run on all python versions it supports.
#          python-version: 3.8

#      - name: Install ansible-core (${{ matrix.ansible }})
#        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

#      - name: Build collection
#        run: make configure-test-ansible

#      # Run the unit tests
#      - name: Run unit test
#        run: ansible-test units -v --color --docker --coverage
#        working-directory: ./build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      # ansible-test support producing code coverage date
#      - name: Generate coverage report
#        run: ansible-test coverage xml -v --requirements --group-by command --group-by version
#        working-directory: ./build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      # See the reports at https://codecov.io/gh/yoanm/ansible-utils-collection
#      - uses: codecov/codecov-action@v2
#        with:
#          fail_ci_if_error: false

###
# Integration tests (RECOMMENDED)
#
# https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html


# If the application you are testing is available as a docker container and you want to test
# multiple versions see the following for an example:
# https://github.com/ansible-collections/community.zabbix/tree/master/.github/workflows

#  integration:
#    runs-on: ubuntu-latest
#    name: Integration (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
#    strategy:
#      fail-fast: false
#      matrix:
#        ansible:
#          # - stable-2.9 # Only if your collection supports Ansible 2.9
#          - stable-2.10
#          - stable-2.11
#          - stable-2.12
#          - devel
#        python:
#          - '2.6'
#          - '2.7'
#          - '3.5'
#          - '3.6'
#          - '3.7'
#          - '3.8'
#          - '3.9'
#          - '3.10'
#        exclude:
#          # Because ansible-test doesn't support Python 3.9 for Ansible 2.9
#          # and Python 3.10 is supported in 2.12 or later.
#          - ansible: stable-2.9
#            python: '3.9'
#          - ansible: stable-2.9
#            python: '3.10'
#          - ansible: stable-2.10
#            python: '3.10'
#          - ansible: stable-2.11
#            python: '3.10'


#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#        with:
#          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          # it is just required to run that once as "ansible-test integration" in the docker image
#          # will run on all python versions it supports.
#          python-version: 3.8

#      - name: Install ansible-core (${{ matrix.ansible }})
#        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

#      - name: Build collection
#        run: make configure-test-ansible

#      # Run the integration tests
#      - name: Run integration test
#        run: ansible-test integration -v --color --retry-on-error --continue-on-error --diff --python ${{ matrix.python }} --docker --coverage
#        working-directory: ./build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      # ansible-test support producing code coverage date
#      - name: Generate coverage report
#        run: ansible-test coverage xml -v --requirements --group-by command --group-by version
#        working-directory: ./build/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#      # See the reports at https://codecov.io/gh/yoanm/ansible-utils-collection
#      - uses: codecov/codecov-action@v2
#        with:
#          fail_ci_if_error: false
